#!/usr/bin/env python3

# TODO
import sys
import os
import helpers
from analyzer import Analyzer
from termcolor import colored


def main():
    
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweet @screenName")
        
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")    
    
    analyzer = Analyzer(positives, negatives)
    
    tweets = helpers.get_user_timeline(sys.argv[1].strip('@'), 50)

    if not tweets:
        sys.exit("Error! screen name doesnot exist or sysname protected!")
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        
        if score > 0.0:
            print(colored(str(score) + tweet + ',' + sys.argv[1], "green"))
        elif score < 0.0:
            print(colored(str(score) + tweet + ',' + sys.argv[1], "red"))
        else:
            print(colored(str(score) + tweet + ',' + sys.argv[1], "yellow"))
        score = 0


if __name__ == "__main__":
    main()